---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_macos: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/micxer/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/dotfiles
dotfiles_files:
  # - .inputrc
  - .macos
  - .gitconfig
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - direnv
  - git
  - go
  - gpg
  - httpie
  - iperf
  - sqlite
  - nmap
  - pv
  - starship
  - wget
  - zsh-completions
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: ~/Applications
homebrew_cask_apps:
  - brave-browser
  - sequel-ace
  - slack

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

macos_defaults:
    # 
  - domain: com.apple.menuextra.clock
    key: DateFormat
    value: "EEE HH:mm:ss"
    # Keyboard
    # Key Repeat / Change the "press and hold" behavior.
  - key: ApplePressAndHoldEnabled
    type: bool
    value: "true"
    # Key Repeat Rate
  - domain: "Apple Global Domain"
    key: KeyRepeat
    type: integer
    value: 2
    # Key repeat delay
  - domain: "Apple Global Domain"
    key: InitialKeyRepeat
    type: integer
    value: 25
    # Full Keyboard Access / Enable Tab in modal dialogs.
  - key: AppleKeyboardUIMode
    type: integer
    value: 3
    # Auto-Correct
  - key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: "false"
    # 
  - domain: "Apple Global Domain"
    key: KeyRepeatNSAutomaticPeriodSubstitutionEnabled
    type: integer
    value: 0
    # 
  - domain: "Apple Global Domain"
    key: KeyRepeatNSAutomaticCapitalizationEnabled
    type: integer
    value: 0
    # 
  - domain: "Apple Global Domain"
    key: KeyRepeatNSAutomaticSpellingCorrectionEnabled
    type: integer
    value: 0

    # Expand Print Panel by Default
  - key: PMPrintingExpandedStateForPrint
    type: bool
    value: "true"
  - key: PMPrintingExpandedStateForPrint2
    type: bool
    value: "true"
    # Quit Printer App After Print Jobs Complete
  - domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: "true"
  - domain: com.apple.HIToolbox
    key: AppleFnUsageType
    type: integer
    value: 2
  - domain: com.apple.HIToolbox
    key: AppleDictationAutoEnable
    type: integer
    value: 1
    

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
